- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: HEAD
  hooks:
    - id: autopep8-wrapper
    - id: flake8
    - id: check-ast
    - id: check-case-conflict
    - id: fix-encoding-pragma
    - id: check-yaml
    # - id: trailing-whitespace
    - id: end-of-file-fixer
